### ISSUE TITLE
allow serial tests with multiple subsets

### ISSUE THREAD

**Issue by zignis** [palfrey/serial_test#101]
the idea is to have multiple subsets for a single test:

```rust
#[test]
#[serial(redis)]
fn one() {}

#[test]
#[serial(s3)]
fn two() {}

#[test]
#[serial(redis,s3)]
fn three() {}
```

`one` and `two` can run concurrently, but the behaviour I desire is that `three` must not run when either of the subsets are running

**Comment by palfrey** [comment]
@zignis https://github.com/palfrey/serial_test/pull/102 should fix this. Can you test out that branch for your use case before I merge that please?

**Comment by zignis** [comment]
> @zignis #102 should fix this. Can you test out that branch for your use case before I merge that please?

Thanks @palfrey , I can confirm that this PR fixes the issue.
