### ISSUE TITLE
#[serial] macro for modules

### ISSUE THREAD

**Issue by xamgore** [palfrey/serial_test#103]
It's kind of tedious to mark each test function with a macros. Is there a way to make all of the functions inside `mod tests { ... }` serial?

**Comment by palfrey** [comment]
TBH, mostly because no-one asked for this before! This looks certainly doable. It'd basically apply the same set of options (`serial/parallel`, etc and the relevant set keys) to all the `#[test]`-marked functions inside a block. Let me have a prod...

**Comment by palfrey** [comment]
@xamgore https://github.com/palfrey/serial_test/pull/104 should do this. Can you test it with your use case please?

**Comment by xamgore** [comment]
I got ill on the weekends, does it still need testing?

**Comment by palfrey** [comment]
The 3.0.0 release has gone out with this in, if you can test that against your use case?

**Comment by ririsoft** [comment]
@palfrey: the mod level `#[serial]` does not seem to work with tokio tests, am I doing it wrong ?

```rust
#[cfg(test)]
#[serial_test::serial]
mod tests {

    #[tokio::test]
    async fn foo()  {
       println!("foo test");
    }

    #[tokio::test]
    async fn bar()  {
       println!("bar test");
    }

}
```

**Comment by palfrey** [comment]
> @palfrey: the mod level `#[serial]` does not seem to work with tokio tests, am I doing it wrong ?
> 
> ```rust
> #[cfg(test)]
> #[serial_test::serial]
> mod tests {
> 
>     #[tokio::test]
>     async fn foo()  {
>        println!("foo test");
>     }
> 
>     #[tokio::test]
>     async fn bar()  {
>        println!("bar test");
>     }
> 
> }
> ```

No, you're not. I made some assumptions about test ident names that weren't actually tested, and only regular tests get matched, not `tokio::test` or any other `<foo>::test`. Looking at that now.

**Comment by palfrey** [comment]
https://github.com/palfrey/serial_test/pull/110

**Comment by palfrey** [comment]
Released as https://github.com/palfrey/serial_test/releases/tag/v3.1.0

**Comment by ririsoft** [comment]
Thanks @palfrey for all the effort, it is much appreciated.
I am still having an issue. I get the error
```
message: called `Result::unwrap()` on an `Err` value: Error("unexpected token")
```

with the following code: 

```Rust
#[cfg(test)]
#[serial_test::serial]
mod tests {

    #[tokio::test]
    #[ignore = "blabla"]
    async fn foo() -> Result<(), ()> {
        Ok(())
    }

    #[tokio::test]
    async fn bar() -> Result<(), ()> {
      Ok(())
    }

}
```

**Comment by palfrey** [comment]
https://github.com/palfrey/serial_test/pull/111 - I'd fixed `blah::test` attributes, but not async ones!

**Comment by palfrey** [comment]
https://github.com/palfrey/serial_test/releases/tag/v3.1.1 🤞🏻

**Comment by ririsoft** [comment]
@palfrey : it works for me, thank you !
