### ISSUE TITLE
 RUSTSEC-2024-0370: proc-macro-error is unmaintained

### ISSUE THREAD

**Issue by vsirivol** [palfrey/serial_test#116]
This repo is using `proc-macro2 v1.0.71` and this is causing the issue.

`proc-macro-error` is unmaintained and is updated to `proc-macro-error2`: https://github.com/jbaublitz/getset/issues/94

`proc-macro2 v1.0.89` has the updated code.

**Comment by palfrey** [comment]
`proc-macro2` can be upgraded in something that depends on this, and now https://github.com/palfrey/serial_test/pull/118 is in, we know that upgrade will still be safe. I don't feel the need to upgrade the dependency here, as we're not blocking other packages from doing that upgrade while using `serial_test`, especially as we don't use `proc-macro-error` directly here.

**Comment by vsirivol** [comment]
Thanks for addressing proc-macro2 upgrade by adding the new step in workflow. But I am a little confused because I don't see that the version update for proc-macro2 is done in the Cargo.lock file. Also I believe according to the workflow trigger, it has to update when there is a push, pull or a crone job that runs every month.

Please feel to correct me if I am wrong or if it takes a little more time before the lock file is updated after pushing the update.
