### ISSUE TITLE
`serial` doesn't seem to serialize `should_panic` tests correctly.

### ISSUE THREAD

**Issue by Monnoroch** [palfrey/serial_test#12]
I assume it has a similar cause to https://github.com/palfrey/serial_test/pull/10.

**Comment by Monnoroch** [comment]
Thanks for a swift fix!

**Comment by Monnoroch** [comment]
Hi, I don't think the fix has worked. I still see a value being accessed from multiple threads when I put a test with `#[should_panic(expected = "upsupported version")]` in the test module.

**Comment by palfrey** [comment]
Do you have a link to some example code that's not working?

**Comment by Monnoroch** [comment]
Sure thing. Here's the [commit](https://github.com/Monnoroch/rust-jni/commit/85008f7a8d1c96ab65d4cb62bdf7b26f0862acd7). It also has a travis CI link with the failures.

Here's the message:
```
failures:
---- vm::java_vm_attach_tests::attach_unsupported_version stdout ----
thread 'vm::java_vm_attach_tests::attach_unsupported_version' panicked at 'trying to access wrapped value in fragile container from incorrect thread.', /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/fragile-0.3.0/src/fragile.rs:57:13
note: panic did not include expected string 'upsupported version'
---- vm::java_vm_with_attached_tests::with_attached_unsupported_version stdout ----
thread 'vm::java_vm_with_attached_tests::with_attached_unsupported_version' panicked at 'trying to access wrapped value in fragile container from incorrect thread.', /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/fragile-0.3.0/src/fragile.rs:57:13
note: panic did not include expected string 'upsupported version'
```

The error message is the same locally. When I move these two failed tests (both `should_panic`) into their own test modules, tests pass. Judging by the error message, I assume the issue is in `serial` tests not being truly `serial`, since the global variables are accessed from multiple threads.

**Comment by palfrey** [comment]
I've managed to at least reproduce part of the problem, in that `should_panic` didn't work if you handed it attributes. #15 should fix this which will get merged shortly.

**Comment by Monnoroch** [comment]
Just tested the commit and it is indeed fixed. Thank you so much! Amazing bugfixing speed :)

**Comment by palfrey** [comment]
Not a problem :) I'll probably put out a new release in a few days or so, once this one's had time for anyone else to bring up more bugs...
