### ISSUE TITLE
Support async test functions

### ISSUE THREAD

**Issue by palfrey** [palfrey/serial_test#22]
@tworec Saw you'd started looking at this. Is this something you intend to continue with, or should I pick this up?

**Comment by tworec** [comment]
Yeah, I've started work on this, but will not pick up in coming weeks.

Pls take a look, and continue if this is similar to what you planning to do
https://github.com/tworec/serial_test/tree/support-async

Cheers!

**Comment by palfrey** [comment]
https://github.com/palfrey/serial_test/pull/23 makes some small changes, but is mostly what you did on your branch. Is there anything else in particular you can think of that needed changing, as I think that you'd done pretty much most of it!

**Comment by cedric-h** [comment]
Can't wait until this is in! It'll be a lot more convenient than `-- --test-threads=1` or `export RUST_TEST_THREADS=1`

**Comment by palfrey** [comment]
@cedric-h If you've got an async test case you want to use with this, would you mind running your code against the `support-async` branch and checking it would work for you if I released that please?

**Comment by palfrey** [comment]
Released in 0.5.0
