### ISSUE TITLE
Is there an option to be serial cross-process?

### ISSUE THREAD

**Issue by gilescope** [palfrey/serial_test#41]
I'm looking at trying to get cargo to run test crates in parallel processes ( https://github.com/rust-lang/cargo/pull/10052 ). It would be cool if there was an option for the attribute to be cross-process serial by locking on a system mutex.

**Comment by palfrey** [comment]
There isn't currently, but there could be. This is the same as the doc test issue (#30) and I've [talked a little bit about possible options there](https://github.com/palfrey/serial_test/issues/30#issuecomment-782615531). It's on my "I should do this at some point" list, but hasn't gotten far enough up yet. Patches welcomed!

**Comment by gilescope** [comment]
ok - let me try and get the cargo pr ship shape first.

**Comment by palfrey** [comment]
https://github.com/palfrey/serial_test/pull/43 should solve this
