### ISSUE TITLE
New release with support for cross-process locking

### ISSUE THREAD

**Issue by gibfahn** [palfrey/serial_test#51]
Started using https://github.com/nextest-rs/nextest, which runs all the test binaries in parallel, but that breaks tests using serial across different binaries.

As far as I can tell from https://github.com/palfrey/serial_test/issues/41 , this is already fixed by https://github.com/palfrey/serial_test/pull/43. So it would be great to get a release with this feature if possible.

Thanks!

**Comment by palfrey** [comment]
[0.6.0 now out](https://crates.io/crates/serial_test/0.6.0). I was waiting on dealing with the stuff around #45, but that's taking a lot longer than I'd originally hoped, so pushing this out now.

**Comment by gibfahn** [comment]
Thanks @palfrey !
