### ISSUE TITLE
Bump MSRV to 1.49

### ISSUE THREAD

**Issue by rukai** [palfrey/serial_test#52]
Please bump MSRV to at least 1.49 to allow updating to parking_lot 0.12.0

I am getting duplicate parking_lot dependencies in my dependency tree because of this.

**Comment by palfrey** [comment]
Are those duplicate dependencies causing compilation or other errors, or are they just annoying?

**Comment by rukai** [comment]
Just increases build time, considering its a dev-dependency it doesnt even increase binary size.
For me its mostly a thousand papercuts kinda deal and im trying to cleanup as many of these occurrences as I can.

To be clear as the maintainer you are free to set whatever MSRV you want, and this can just stay a papercut until you are ready to bump the MSRV. I think my original comment was worded too strongly...

A useful outcome of this issue would be to at least document the requirements for bumping the MSRV and/or what its aiming to support e.g. usually people have an MSRV to maintain compatibility with the rust shipped by a certain distro or something.

**Comment by palfrey** [comment]
My general thinking is "keep it as low at possible as that'll support more things", but I'm not explicitly monitoring anything external. It gets bumped when there's something we need for a feature or someone reports that it's more causing build failures.

OTOH 1.39 is pretty old now. I'll have a think about sensible policies on bumping that and come back to this in a few days.

**Comment by palfrey** [comment]
#53 fixed this, but it's not released yet. I'd like to fix #42 before the next release, but we'll see how that goes. Depends on my available time, which isn't exactly a lot.
