### ISSUE TITLE
Nested calls to #[serial] tests results in a deadlock

### ISSUE THREAD

**Issue by sagar-solana** [palfrey/serial_test#6]
Within a test with the `#[serial]` annotation, calling another `#[serial]` test results in a deadlock.

Consider the following example: 
```rust
#[test]
#[serial]
fn test_fun() {
    assert_eq!(1 + 2, 3);
}

#[test]
#[serial]
fn test_not_fun() {
    test_fun();
}
```

Running `test_not_fun` results in a deadlock.

**Comment by alexlapa** [comment]
@sagar-solana ,

Switching from std's Mutex to `parking_lot::ReentrantMutex` would solve this issue, but im not sure why anyone would try to do something like in your snippet :)

**Comment by sagar-solana** [comment]
I don't feel too strongly about this but I've seen patterns like this before. Ideally they'd factor out test_fun so it's not a huge deal. Maybe just needs to be noted somewhere?
