### ISSUE TITLE
Possiblity to disable dependency on `futures`?

### ISSUE THREAD

**Issue by Urhengulas** [palfrey/serial_test#73]
Hello,

Thank you for your library! We are using it in https://github.com/knurling-rs/probe-run and it comes in very handy 😁 

I am just upgrading from `0.5.1` to `0.8.0` and am seeing that this adds the additional dependency `futures`, which in turn pulls in  "futures-channel", "futures-core", "futures-executor", "futures-io", "futures-sink", "futures-task" and "futures-util". Which is a lot 😵‍💫

Since we are not using any async functions, is there the possibility to make this dependency optional by hiding it behind a (default) feature?

👋🏾

**Comment by palfrey** [comment]
Previously, I would have said "no", because I seemed to recall trying to do this when implementing the async support to begin with and it didn't work. But I've just poked at things again and it looks doable. Should have a PR for this at some point...

**Comment by Urhengulas** [comment]
> Previously, I would have said "no", because I seemed to recall trying to do this when implementing the async support to begin with and it didn't work. But I've just poked at things again and it looks doable. Should have a PR for this at some point...

Thank you for taking this on! 🙇🏾‍♂️

**Comment by palfrey** [comment]
https://github.com/palfrey/serial_test/pull/74 is the start of things, and it probably just needs some minor more fixes to resolve out some cases of some particular combinations of features not working well together TBH.

**Comment by palfrey** [comment]
The `optional-async` branch from #74 LGTM, but if you could test this out with your use case please before I merge that?

**Comment by Urhengulas** [comment]
> The `optional-async` branch from #74 LGTM, but if you could test this out with your use case please before I merge that?

I will test it! Thank you!

**Comment by Urhengulas** [comment]
I just tested it and now `serial_test` does not pull in all the `futures-*` dependencies anymore! Thank you!

I guess you could publish that as a patch release, since the `async` feature is enabled by default, right?

**Comment by palfrey** [comment]
I'm planning a 0.9.0 release soon with some other stuff and this will get folded into that.

**Comment by Urhengulas** [comment]
> I'm planning a 0.9.0 release soon with some other stuff and this will get folded into that.

Nice. Thank you very much!

**Comment by palfrey** [comment]
Released as part of 0.9.0
