### ISSUE TITLE
Can't `pub use` a test function marked with `#[serial]` in a private module

### ISSUE THREAD

**Issue by bl-ue** [palfrey/serial_test#80]
I'm trying to export a specific `#[test]` function so it's available outside of the enclosing `tests` module (which is private) using `pub use`, so a different test in a different file can run it. However, when I add the `#[serial]` attribute to the function, the `pub use` stops working and I get this compiler error:
```
error[E0603]: function `test` is private
 --> src/main.rs:1:16
  |
1 | pub use tests::test;
  |                ^^^^ private function
  |
note: the function `test` is defined here
 --> src/main.rs:6:5
  |
6 |     #[serial]
  |     ^^^^^^^^^
  = note: this error originates in the attribute macro `serial` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Here's `main.rs`:
```rust
pub use tests::test;

mod tests {
    use serial_test::serial;

    #[serial]
    pub fn test() {}
}
```

`rustc --version --verbose`

```
rustc 1.67.0-nightly (42325c525 2022-11-11)
binary: rustc
commit-hash: 42325c525b9d3885847a3f803abe53c562d289da
commit-date: 2022-11-11
host: x86_64-apple-darwin
release: 1.67.0-nightly
LLVM version: 15.0.4
```

**Comment by palfrey** [comment]
Yeah. The macro generated tests [don't have `pub` marked on them](https://github.com/palfrey/serial_test/blob/main/serial_test_derive/src/lib.rs#L450). OTOH, the right value here can be figured out from the [visiblity field](https://docs.rs/syn/0.15.44/syn/struct.ItemFn.html#structfield.vis) in the same way as we figure out [async/non-async](https://github.com/palfrey/serial_test/blob/main/serial_test_derive/src/lib.rs#L376).

Should probably generalise out the generation functions to avoid having to make _8_ slightly different versions...

**Comment by bl-ue** [comment]
> Should probably generalise out the generation functions to avoid having to make _8_ slightly different versions...

If I'm right, that shouldn't be necessary. I added `#vis` to each of the 4 function definitions (where `vis` is the `visibilty` field you linked) and it seemed to work for private and public functions, with and without `async`.
