### ISSUE TITLE
Add exclusive attribute for serial_test ?

### ISSUE THREAD

**Issue by eval-exec** [palfrey/serial_test#86]
serial_test is awesome.

Consider the following scenario: 

There are many unit test( `test0, test1, test2, test3, test4, test5 ...` ) in a project, I want to organize `test{0,1}` run as serial and I don't want `test{0,1}` run as same time as `test{2,3,4,5}`.

so I have to add `#[serial]` to `test{0,1}` and add `#[parallel]` to `test{2,3,4,5}`, since:

> tests with the parallel attribute may run at the same time as each other, but not at the same time as a test with serial

this solve the problem, but it's inconvenient.

So I think it would be more convenient to add `exclusive` attribute to `serial`, just add `#[serial][exclusive]` to `test{0,1}`, this make `test{0,1}` run as serial and exclusive with others tests. 

Do you think it's a good idea?

**Comment by palfrey** [comment]
It's a great idea. It's just _mostly_ not possible. So the reason we need the attributes added to all the tests you don't want running at the same time is so `serial_test` has some control over them. They effectively add a little wrapper around the tests and only release one at a time to run. Any test that is missing both `serial` and `parallel` is completely free to run whenever, and `serial_test` has no control over that.

The only way to make this work is with a custom test runner. In theory you could do something by setting [harness to false](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#the-harness-field) and then building something that deals with all the consequences of that and supports your use case. I'm not interested in doing that in `serial_test` as it'll have a whole other set of problems that aren't really the focus of this library, but you could build something external that uses `serial_test` and automagically adds `parallel` to every untagged test. Or it could be built into something like [cargo-nextest](https://nexte.st) if they're willing.

**Comment by sunshowers** [comment]
Just as an update, nextest now has support for this: https://nexte.st/book/test-groups.html

**Comment by palfrey** [comment]
Awesome. This was in 0.9.48 and https://github.com/nextest-rs/nextest/pull/736 just for the record.
