### ISSUE TITLE
Optional test prefix to make nextest filtering easier?

### ISSUE THREAD

**Issue by chamons** [palfrey/serial_test#89]
There are two test runners commonly in use to my knowledge: `cargo test` and `cargo nextest run`.

serial_test completely covers the use case of thebuilt in test runner. Howver, as [documented in nextest](https://nexte.st/book/test-groups.html#test-groups-and-mutual-exclusion) it does not work in nexttest:

>  NOTE: Nextest does not support in-process mutexes (or semaphores), directly. Instead, you can emulate these features by using test groups.

A simple solution that I've tested locally is to rename each test to have a prefix:

`fn foo () -> fn serial_foo ()`

and use a configuration file for nextest like this:

```
[test-groups]
serial = { max-threads = 1 }

[[profile.default.overrides]]
filter = 'test(serial_)'
test-group = 'serial'
```

I have a local change that extends serial_test to optionally do this rename automatically. 

Would there be interest in a PR that does that, either through a configuration option OR a new top level attribute?

**Comment by palfrey** [comment]
Maybe. I'm trying to understand the goal here. Is it that you have a test called `foo` which has the `serial` attribute and then instead of the `serial` attribute spitting out a same-named test after the proc attribute mangling it spits out one called `serial_foo` so you can then do filtering? How does this work with `parallel`?

I'm overall not a fan of doing things that are too locked down to one other tool, but this might be viable.

**Comment by chamons** [comment]
Yes, that is the general idea:

- Say I have 500 tests and 100 of them use Redis and have to be run one at a time
- I want to be able to run those tests with cargo test and nextest
- serial_test's [Serial] attribute solves the problem for cargo test, but nextest doesn't have a filter for attributes
- However, it can filter based on test name
- So create a new attribute (or configure the existing one), to change the name to have a prefix that nextest can also filter on.

I admit it's a bit of a strange feature request, but nextest has some nice performance benefits and supports CI test reporting, so we want to support both. 

Today I could mandate that each test have the [Serial] attribute and have a certain name, but someone is bound to forget at some point. Being able to solve both with one attribute sure would be nice.

**Comment by palfrey** [comment]
> but nextest doesn't have a filter for attributes

Can't this be fixed instead?

**Comment by chamons** [comment]
I am not a developer on that project, but reading over [the execution model](https://nexte.st/book/how-it-works.html) they run each test in a separate process, so process specific locks won't be helpful.

I reviewed the 'cargo expand' output, and I don't see anything from the serial attribute that nextest could filter on beyond the name. Attribute macros don't make their way to the final binary unless they modify generated code in some detectable way.

Thinking about it this morning, it occurred to me that this doesn't actually have to be in serial_test itself proper, however. You could create an attribute macro that adds the [Serial] macro AND does the rename, and use that as a higher level to paper over the differences.

The downside would be that assuming nextest becomes more widely used over time, directly using serial_test would be possibly less useful.

**Comment by chamons** [comment]
I was able to implement a macro that combined a rename + add the serial attribute, so that solved my use case at least.

If you consider nextest support out of scope, feel free to close this issue.

**Comment by palfrey** [comment]
Thanks for the exploration work. Given there's a viable solution that doesn't require changing `serial_test`, I'd definitely regard nextest support as out of scope.

**Comment by qrilka** [comment]
@palfrey if you say that nextest is out of scope, probably this should be mentioned in the docs?
I see concurrency problems in our tests using `serial` when run with nextest. This seems to be solvable by `file_serial` though.

**Comment by palfrey** [comment]
> @palfrey if you say that nextest is out of scope, probably this should be mentioned in the docs? I see concurrency problems in our tests using `serial` when run with nextest. This seems to be solvable by `file_serial` though.

I'd note they already have docs about it https://nexte.st/book/test-groups.html#test-groups-and-mutual-exclusion and that is probably where it should be documented.

**Comment by qrilka** [comment]
It's your crate so I could only give a suggestion but it would be odd to see nextext documenting that it's out of scope for `serial_test`.
