### ISSUE TITLE
Update serial_test_derive syn dependency to syn 2

### ISSUE THREAD

**Issue by jtroo** [palfrey/serial_test#95]
Syn 2 was released recently and some crates, e.g. thiserror, are already migrated. To reduce clean compile times, should upgrade dependency to syn 2.

**Comment by palfrey** [comment]
This won't help until tokio-macros upgrades. See https://github.com/tokio-rs/tokio/blob/master/tokio-macros/Cargo.toml#L27

**Comment by jtroo** [comment]
This is now unblocked as tokio-macros has upgraded 🙂. No pressure to rush on this, just a friendly unblocking notification.

**Comment by jtroo** [comment]
One thing I noticed in other repos is that syn 2's MSRV is `1.56`, so according to the README,
> We require at least Rust 1.51. Upgrades to this will require at a major version bump.
Updating to syn 2 will require a major version bump.

**Comment by CosmicHorrorDev** [comment]
I'm up for giving the update a go if ya want the help @palfrey

**Comment by palfrey** [comment]
> I'm up for giving the update a go if ya want the help @palfrey

No, that's fine. The upgrade here is pretty simple, but I want to write some specific docs about the MSRV bump as I'm planning on bumping it all the way to 1.68.2. This is more than compilation requires right now, but mostly for a future-proofing perspective i.e. reducing the odds of having to release a 3.x when something else bumps.

**Comment by palfrey** [comment]
https://github.com/palfrey/serial_test/pull/96 fixes this

**Comment by palfrey** [comment]
Released as 2.0.0
