### ISSUE TITLE
OnceLock statics shared across serial tests

### ISSUE THREAD

**Issue by cmleinz** [palfrey/serial_test#99]
I have a need to set some static variables before testing. I was hoping to be able to use serial_test to ensure the changes to the statics are not consumed by other tests. However this doesn't appear to be the behavior (one of the two tests always fails). Am I correct in guessing that this is because unit tests annotated with `#[serial_test::serial]` doesn't run tests as separate processes in the same way integration tests do, and thus still share statics defined in this way? 

Perhaps accommodating this is just not possible with unit tests, but I want to ask. Thanks for your work on library!

```rust
#[cfg(test)]
mod tests {
    use std::sync::OnceLock;

    static FOO: OnceLock<Vec<u8>> = OnceLock::new();

    fn common_functionality(data: Vec<u8>) -> Result<(), Vec<u8>> {
        FOO.set(data)
    }

    #[test]
    #[serial_test::serial]
    fn test1() {
        let data = vec![0; 1024];

        assert_eq!(common_functionality(data), Ok(()));
    }

    #[test]
    #[serial_test::serial]
    fn test2() {
        let data = vec![0; 512];

        assert_eq!(common_functionality(data), Ok(()));
    }
}

```

**Comment by palfrey** [comment]
> Am I correct in guessing that this is because unit tests annotated with #[serial_test::serial] doesn't run tests as separate processes in the same way integration tests do,

Correct. We do support [file_serial](https://docs.rs/serial_test/latest/serial_test/attr.file_serial.html) tagging for integration tests that want serialisation, but fundamentally standard `serial_test` tests do just use the standard Rust test runner.
